spring:
    jpa:
        hibernate:
            ddl-auto: update
    datasource:
        url: ${JDBC_DATABASE_URL}
        username: ${JDBC_DATABASE_USERNAME}
        password: ${JDBC_DATABASE_PASSWORD}
        initialization-mode: always